# Generated by Django 4.2.1 on 2023-05-16 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Содержимое')),
                ('departure_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправления')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='PrivateMessage',
            fields=[
                ('message_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tours.message')),
                ('recipient_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_person', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
                ('sender_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_person', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
            ],
            options={
                'verbose_name': 'Личное сообщение',
                'verbose_name_plural': 'Личные сообщения',
            },
            bases=('tours.message',),
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('message_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tours.message')),
                ('title', models.CharField(max_length=120, verbose_name='Заголовок')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tours.tourismmanager', verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
            bases=('tours.message',),
        ),
    ]
