# Generated by Django 4.2.1 on 2023-05-19 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_message_privatemessage_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='news_covers/', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='message',
            name='departure_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время отправления'),
        ),
    ]
