# Generated by Django 4.2.1 on 2023-05-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_news_cover_image_alter_message_departure_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tours/', verbose_name='Обложка'),
        ),
    ]
